apiVersion: ENC[AES256_GCM,data:ZlQ=,iv:7jT/FdwSQUIQ7Jv5kfKHZgEh/u4s2aiZk8DkWoRuiMo=,tag:CoPUzAgZat9jc51KbEXjzw==,type:str]
kind: ENC[AES256_GCM,data:S8yGPlMZ,iv:ttTa1BoIaMqc+53GClKa1d8B7VBjjTA8lxHe3l481rk=,tag:TD3Gs2eo3520UyC2fT6TzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:6r/nTSIE4fAu9u125B/S5tBjKwueMw==,iv:tFwA8FB+i3kKYp4TcWZBBSz7j/HjWjL06kLxlbfsVHM=,tag:u9JISpvTuF0s+ZbIlLNOTA==,type:str]
    namespace: ENC[AES256_GCM,data:Hpkeo4q/,iv:pFU3dcSWVoL82q3ESU6ls5SCBt6FWdn2qksiorvX+rw=,tag:JshXIFRWCNOhanA7TaJcZQ==,type:str]
type: ENC[AES256_GCM,data:6uKMRxC1,iv:JbGTXPTmp7MeHQzJu52pAXJz4UbxQ7wxCg5LfF8oZnI=,tag:iLyUseNEl2T+l1X9j0GWMQ==,type:str]
stringData:
    serviceAccountToken: ENC[AES256_GCM,data:k5V+SJLiVC3JUBzBGyEi/O+73WC/jGl7gzKzrov2gck9bzaArAc1jRJCecTp8Q==,iv:7HXppTlO/uAYVBmhKNmar/QGKzI6/KFDScMXWEi9owk=,tag:MC16e+l0bkQ93xFbyZ+3GA==,type:str]
    webhookSecret: ENC[AES256_GCM,data:kQX2CAcJiDlYXC9urVZuzEYKql8qk6GZ+MwfGe48t/Rc0Man6K7cWZLrJ89K7bzp,iv:LtVtd8bkrS9c2GKb2HOd2dLNTpI9KAjLS1f2znvfW2U=,tag:lFd2GPz+pLvDSrwU2v1nXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-20T07:08:10Z"
    mac: ENC[AES256_GCM,data:GCqnxYLqKqOrZJyrP0V28Yfd/GaTIn1fOzWT4EJiXnjFXKpNjl6Sv0p/llhDUTiruIse+/zCAdF2tNT369p0bXB6nNVzP6jT8o4FO0FMeGnEG5rcTI3YLCVV9pN6j90x5tXyUkz15cfWPHQmygUgzFany+9MByEP4MnA5nQ4sQE=,iv:ELlXmcGKu7rc5l1MF78qB4r90dFuv/AwqDvUkMhWcCs=,tag:C2AnFFL8Z67+wAZdjhgnJA==,type:str]
    pgp:
        - created_at: "2026-06-20T07:08:10Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQILAwGxy666b7DTAQ/3eyazl0wLRGrSwdMkCZcS0rSnuEn3UctEqMs0RdUahlvR
            OWohIV29DaBN+SJh+iSTDy6NyyAMt37m6P9aD/2LjuNNL9ZKq5csfHCEJNQ5BTuf
            AugRJR+EPGMdHQxI6fwfNOsJBmTjJyYd+9S4xmMb5ni2/uJrmlWgaSufCBlPfO1x
            FD5LgSnGrFvkcTXscTZXy1fjDBBj+SXbmFj7sLWadoNEo1PS2JmjSMNmfCBZPL0F
            G4U5UwXgSmLUpdbeCksKx4O8ek+XlE/JAv4XzjCuDgyIUCeIOXftZRVYe2CljQ10
            ug1pFtd9xNkhuov+S/J/47A4WK8GHeFMBb6s3A6kbmop5O1L20fbJtPwRGvp1DIZ
            P8j+VB3Wstz0VjSTTHNptMcKwMO1mYzVTf2J+H1FJiOdsa7fy8TNwtrPURcjPHeW
            6iJ4azGtbZ/LIj8xMjMXqHpImN5yO9k5Uf7husXcQU3nkMx5JqWJ6W9qvBqrjziI
            6TcT0m7kAzqSlKhPn550dlKhaKk4xha6vNZO+j56UiiLNxXMu58dutFHvbOJVlwF
            wL+sOET4z0AEe0xvRHf/ZlnI6Xn/bx8w1M8pgKS7p8vDQ4SC4cSA+YgyPzDXqZIm
            KAdHc+bvVT6d0EsZAJ/2mgoqHnM8M08oF2rT1iI/j0HBELVhRbQUhh3gFy+XfdJc
            AfM9yTRrLJHFUdrA92V3U88sfysz+5PVgfHrLhbLr9kYJHGMPDKoy0z/eaUTTDOH
            63ozw2PQhKaPG0eGNWycfPn7wkxjGFI8GkqvV+GqkM4poBTskopyCfz1gvg=
            =6b5w
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.9.1
