apiVersion: ENC[AES256_GCM,data:mDw=,iv:UQkV+5fpa692THllBEkskrHtZeR/mcMHHo99etMCNd8=,tag:8b/qrLryhdhn1zuVpmlAvQ==,type:str]
kind: ENC[AES256_GCM,data:Ihq3uAd6,iv:kiZOuAu5g3F74+8CKCnk2AH0eYvDCmGr1eAkPOC6ou4=,tag:cWbEjyXgMKU+ynYP8vtyzw==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Q63rLrwmGLoFHRLKsSgXDXDF,iv:sXIdJVWtu65oZNj20KsqFDOxlSDJSPRjhGoWY2R+iRQ=,tag:wiucVTLGP47dFPPTC+WYNw==,type:str]
    namespace: ENC[AES256_GCM,data:dgfXPSzu,iv:6ZwA6I7d3m3KIZfqukE40rY7X2jdQHaYywzCoOCRQik=,tag:F0WRU1U0egvz/pXghPOYxw==,type:str]
type: ENC[AES256_GCM,data:2154QtdA,iv:aN2+r5l3d7SQ773ARdz32WkmuzxIjfhYJu5ksRpnnMg=,tag:+nLN/0vFNinhWmV1Fh0N6w==,type:str]
stringData:
    token: ENC[AES256_GCM,data:2AODdvyO+CTmL2Z60FL0xThqx1enVY8ANWyXZj7eCxuhO5RuQefqt31+B1/fiWMgovq6TWQ/Lg8CO8ICzwk=,iv:Umh8R97QBOAv/bFz5E70MDca4kRDmJ2Ht6zpAhas518=,tag:GN2KTwXhX0L+8Lfx4QfGyg==,type:str]
    webhookSecret: ENC[AES256_GCM,data:uaj/fpYnANzAk2CPlGra39ELXAI1hymlyqR5uxcUBXQg2eNK5IZ7c0Kh0t2ePFZ7,iv:wEPSB4/sdO700EPmGSSG+uQTknVGs9W9usLW1ufXNqI=,tag:y9s+qcHjbcvBXGDOFwo+cA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-20T06:14:53Z"
    mac: ENC[AES256_GCM,data:XjcwUUhu/Bo2vAjfytP4Qpg3BVBov6ZvyP+XFJ4B/sKrXVB7ejLNlLRYGF5yRCv9WyVwNJxxw1AvqCmPzmjjwKUn2dePc03R5AtDMl6teVbJKGCN1ao+1DXOl2kpoTwb4zu2mORDi3FJK20au2eBIQGOPrRy8baF9gyUU0x8Zb0=,iv:zSLQUN/88o6OWHKjC2/mLXcIZpg9e6jVldHGbXDqdFs=,tag:UiSlCXAKYCKHQrZGvrbOVA==,type:str]
    pgp:
        - created_at: "2026-06-20T06:14:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTAQ/9E8n2auCbqPvtG2A5qYXoQXG75FrkNcwgR0HoS5iLRqRB
            71Ggitz5jN6C3DJ8kpKgifK93/BZo3WOTMIJvueLuRYQKHunTDvvKda1KcS2Lanq
            eqPM5kFnq/siCCY4aAk36JS5I5CSIo7TPKtW0WBLjs1fU5LNcMa3bvbNFhEZjIJJ
            gc3LRrvpFQwj7Q+ir1J/SjyCq2cSbFbe9LSyhb8FEn8SkiS5MGrlrhg87mdSrVTN
            3tlC4Lqwm0iRWpCPMN617DweKmXajLG6s6rRbnQeIPwg8GJHZRPmv5BRpygDLrCN
            6B0u5SUc2+piMnHfFL1rZL/v9fRve7Zx24lnZURopOXvk1Dw0tg+al5AKwWkiSVu
            8eg6JXpbQ+S7VX4pPfMFVmWatNRCrL5Bhja2uvQSEjL0ALa9myBA+MY4Q+O4d3Sh
            /m0ZzHzfuCWSTFk+2TaPwDon/SG9W3+u9qft10vBrJTNzAPnhLWMrAnXdjlqknIO
            cphUZd0gZhA+86w4xpJUa+hOji5Iba7zfujSsGumi5pNT3NW4tvLfxHATr6DgbAx
            ZPFeU5OEHI/v4VufsyCqVRwpYGzfbvScMRT3ED/p0lzbkKWayMKbcNe6Y8c5KHXY
            OZnWNIH//1we18um3iWGysBdcOYpb34kGATlW+WTA+EhXhG2N0L7b8bNxDcHrgHS
            XAEbpVFFHQpo57k26/VaqBtXVg6Ryy5ED3aI4GFQ6A6Z/1WsGfd86oF+UTUKMW0Q
            IxzkHtcEAO8u1PXRmG4u7/gw/477SeUx2WgUtuVX9/nvqlwkP8Ie1nU1czoK
            =TexR
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.9.1
