apiVersion: ENC[AES256_GCM,data:0/k=,iv:+ggjoKWPvMkvSD9fJQQOUM8S/+VAIoQtRKzbQ40OMc4=,tag:yYWuHUjydbfRbFbTmuspPw==,type:str]
kind: ENC[AES256_GCM,data:VElJsUPF,iv:G4HgRbcl9devf9dMUCcvscmEK7qFyAXFkaHB72ssvnM=,tag:iiGTR1GptOuEaSWSc8tuzA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:Mb8T93pMmZlCGKt2M2M=,iv:NCPtsoqqhVhqDCYu8qQ9RIpR+3LhZ7L1sDOHyAaYksA=,tag:JFwoYjX6K00F+dlpmV80ug==,type:str]
    namespace: ENC[AES256_GCM,data:GQ1L/+Xj,iv:0mFH+oJ5gjficmuJ4Vb9lk8hZ4NNfH42QaZ3oWMC4/M=,tag:4NnFPfMUuNE8hLPg+Tk2hQ==,type:str]
type: ENC[AES256_GCM,data:wGDizD/H,iv:MWmSM+rBCOPB5e3xF5bRNMxzPG/jya6RxBWQZXYP/rg=,tag:/H+RjQL9Dsel/wqQwDnblg==,type:str]
stringData:
    serviceAccountToken: ENC[AES256_GCM,data:/kQtUXOhehCjjx7CZcakZCtQOjR5tSQe9F+EMz28lP88rnaelMlKqUPJ2JYXSg==,iv:EcJDmJ74+C/rqN+9Zvem37bPc64u2OHRWY8QxM6RLnw=,tag:FvGeyznQM9Hg+b+ve9EX4g==,type:str]
    webhookSecret: ENC[AES256_GCM,data:iJrTCCFJEbJysbrNl/ft0P7JvK52uqAX+YXAvR3+VbU/wsEGPQfN5QlD9AHVqIbd,iv:xLPTBKf9ZYkSCutwYX+XlmIn9IG5msuFYgBtvYry3N0=,tag:IQW0053nqSYyjYRrD2sP6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2026-06-24T19:04:15Z"
    mac: ENC[AES256_GCM,data:rb6jXGQPYDQXNeeAZm2bi8i7k+u8f6gFHEO3MZD1jrKyePZNd4ffiWoFbv5YMtZjEGM5IrgJ4l2n9awEJUZmI0K+V+7nRsAp4JUy+a9ODIMdjmTji111wE00YjKe8T962yeJzoF7Oe7ScwkvQnhwd369EALXLbhZJws3d/uWSQU=,iv:Iq23DG/HhC3BG9qtYtPiO3/uPMplMYqvquBdUqfCmdE=,tag:+/tFekQmSGGccevZ2JAu4w==,type:str]
    pgp:
        - created_at: "2026-06-24T19:04:15Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMAwGxy666b7DTARAAgpTYX6Ob+NAdLqSAfpGXtQWi9f2dJOj/CrIC2QiWnHkV
            JoIiC+uVZhEJXaXy8ND8xGAomCeVyQJUYIw5Q+omVHE9FWebH1pSsoCVlONSt+U5
            4/z1fC3QJnqObraCrZqi3Azo+haUEcKk+5cid6svcARGDlDkrv+V3Zq8BohhaZQY
            1RD47Qc7Qlx4v2ntPYk8yfO8ZXGRiBpXLvQXW1rytv9eiQf3mBvcb7s5BhzZ+Pdn
            IBfavTuQWbk7DKKZ2hRKuDetFsifI23PHKKJCI1jogNiTRfsWxrZDZlM7Cv7tkzY
            srgCqua/4iPEMf1QxCuHIM9UaHOiOX/09OsDFy1R6+eOf1jvztYSAsT4pQcelaAY
            sJ6bKLBufhyV2Q1RCRQDhcgQVr/kPO8Q+uotqqyYgZTYtlLiEhtSYDQW45/U39di
            /d0i0kh4FyXiWgg2nMxlcs5bqNAj2X9C4VZ5dUE+r4yVVGal/ZUjW6lMW6ly9pSX
            HRyX5KeZl1mLbAz5YZZIloMfjUdy5DRflbhA1w1WwQcQJjlUOCNw6QbzQ1PWpDjE
            W0Xwq22hAZ5TpR6462+9+nxbwnMsE6p0s40ITJgfd3FVKVSAL4cZj6G8eEKh2iRA
            2x+EjFRVe+LqLYvtin7kWax1L4YaPmjqr16n7vtja6Km7scxfY+091wGV4dhOV/S
            XAHeUeoFG5hZwZ3JVaV78auccGNrOfcIMFfXrRRJdkcxsOR1pCSRERjeUU5huQ2D
            4YWK1nVx+/ByCwh7+6rfzLcBzPNprfVDOFE3ZLQkimFrmraFJWstS6lY/KLd
            =KUFr
            -----END PGP MESSAGE-----
          fp: D39E46932A270AA3BA490B9DB9FE928D3E8BCED8
    unencrypted_suffix: _unencrypted
    version: 3.9.1
